In [287]:
import numpy as np 

In [ ]:
np.array([2,4,56,422,32,1]) #1D aaray

In [5]:
a = np.array([2,4,56,422,32,1]) #Vector
print(a)

[  2   4  56 422  32   1]


In [7]:
type(a)

numpy.ndarray

In [11]:
# 2D Array (Matrix)
new= np.array([[45,34,22,2],[24,55,3,22]])
print(new)

[[45 34 22  2]
 [24 55  3 22]]


In [13]:
#3D array # Tensor
np.array([[2,3,33,4,45],[23,45,56,66,2],[357,523,32,24,2],[32,32,44,33,234]])

array([[  2,   3,  33,   4,  45],
       [ 23,  45,  56,  66,   2],
       [357, 523,  32,  24,   2],
       [ 32,  32,  44,  33, 234]])

dtype

In [15]:
np.array([11,23,44], dtype= float)

array([11., 23., 44.])

In [19]:
np.array([11,23,44], dtype=bool) #nonzero is True

array([ True,  True,  True])

In [21]:
np.array([11,23,44], dtype= complex)

array([11.+0.j, 23.+0.j, 44.+0.j])

arange

In [6]:
np.arange(1,25) # 1 included, 25 last one got excluded

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [8]:
np.arange(1,25,2) # 1 to 24 with 2step

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

reshape

In [11]:
np.arange(1,11).reshape(5,2) # arange 1 to 10 number in 5 rows and 2 column

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [13]:
np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [15]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

ones and zeros

In [18]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

random

In [23]:
np.random.random((4,3))

array([[0.94908068, 0.23402312, 0.06583647],
       [0.19992386, 0.05312534, 0.6913203 ],
       [0.35102987, 0.93365012, 0.53219524],
       [0.80060977, 0.96885912, 0.91283758]])

linspace

In [26]:
np.linspace(-10,10,10) #numbers from -10 to 10 with 10 equal distance points

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [28]:
np.linspace(-2,12,6) #numbers from -2 to 12 with 6 equal distance points

array([-2. ,  0.8,  3.6,  6.4,  9.2, 12. ])

identity

In [31]:
np.identity(3) #diagonal items will be one and everything will be zeros

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [33]:
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

array attributes

In [36]:
a1= np.arange(10)
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
a2= np.arange(12, dtype= float).reshape(3,4)
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [40]:
a3= np.arange(8).reshape(2,2,2)
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

ndim= to findout given arrays number of dimensions

In [43]:
a1.ndim

1

In [46]:
a2.ndim

2

In [48]:
a3.ndim

3

shape = gives each item consist of numbers of rows and columns

In [51]:
a1.shape

(10,)

In [53]:
a2.shape

(3, 4)

In [55]:
a3.shape

(2, 2, 2)

size= gives number of items

In [58]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [60]:
a3.size

8

In [62]:
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [64]:
a2.size

12

item size= memory occupied by the item

In [67]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
a1.itemsize #bytes

4

In [71]:
a2.itemsize #integer 64gives = 8 bytes

8

In [73]:
a3.itemsize #integer 32 gives = 4 bytes

4

dtype = data type of items

In [83]:
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int32


Changing Data Type

In [86]:
x= np.array([33,22,2.5])
x

array([33. , 22. ,  2.5])

In [88]:
x.astype(int)

array([33, 22,  2])

Array operations

In [91]:
z1= np.arange(12).reshape(3,4)
z2= np.arange(12,24).reshape(3,4)

In [93]:
z1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [95]:
z2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

Scalar Operations

In [98]:
z1 + 2 #arithmetic

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [100]:
z1- 2 #substraction

array([[-2, -1,  0,  1],
       [ 2,  3,  4,  5],
       [ 6,  7,  8,  9]])

In [102]:
z1 *2 #multiplication

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [104]:
z1 **2 #power

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [106]:
z1 % 2 #modulo

array([[0, 1, 0, 1],
       [0, 1, 0, 1],
       [0, 1, 0, 1]], dtype=int32)

Relational Operators or comparison operators( returns only true or false)

In [110]:
z2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [112]:
z2 > 2 #if 2 is greater then the items gives True

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [114]:
z2 > 20

array([[False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True]])

Vector Operation

In [117]:
z1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [119]:
z2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [121]:
z1 + z2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [123]:
z1 * z2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

In [125]:
z1 - z2

array([[-12, -12, -12, -12],
       [-12, -12, -12, -12],
       [-12, -12, -12, -12]])

In [127]:
z1 / z2

array([[0.        , 0.07692308, 0.14285714, 0.2       ],
       [0.25      , 0.29411765, 0.33333333, 0.36842105],
       [0.4       , 0.42857143, 0.45454545, 0.47826087]])

Array Functions # 1 is row, 0 is column

In [130]:
k1= np.random.random((3,3))
k1= np.round(k1*100)
k1

array([[91., 77., 14.],
       [22., 93., 47.],
       [84., 54.,  2.]])

In [132]:
np.max(k1)

93.0

In [134]:
np.min(k1)

2.0

In [136]:
np.sum(k1)

484.0

In [138]:
np.prod(k1) #prod ---> Multiplication

85578896475072.0

In [140]:
# if we want maximum of every row
np.max(k1, axis= 1)

array([91., 93., 84.])

In [142]:
#maximum of every column
np.max(k1, axis = 0)

array([91., 93., 47.])

In [144]:
# product of every column
np.prod(k1, axis = 0)

array([168168., 386694.,   1316.])

Statistical Related functions

In [147]:
k1

array([[91., 77., 14.],
       [22., 93., 47.],
       [84., 54.,  2.]])

In [149]:
np.mean(k1)

53.77777777777778

In [151]:
k1.mean(axis = 0 ) #mean of every column

array([65.66666667, 74.66666667, 21.        ])

In [153]:
np.median(k1)

54.0

In [155]:
np.median(k1, axis= 1) #median of every row

array([77., 47., 54.])

In [158]:
# Standard Deviation
np.std(k1)

32.82200406156339

In [160]:
np.std(k1, axis =0)

array([31.00895928, 16.00694294, 19.02629759])

In [162]:
# variance
np.var(k1)

1077.2839506172838

Trignometry Functions

In [165]:
np.sin(k1)

array([[ 0.10598751,  0.99952016,  0.99060736],
       [-0.00885131, -0.94828214,  0.12357312],
       [ 0.73319032, -0.55878905,  0.90929743]])

In [167]:
np.cos(k1)

array([[-0.99436746, -0.03097503,  0.13673722],
       [-0.99996083,  0.3174287 , -0.99233547],
       [-0.6800235 , -0.82930983, -0.41614684]])

In [169]:
np.tan(k1)

array([[-1.06587872e-01, -3.22685758e+01,  7.24460662e+00],
       [ 8.85165604e-03, -2.98738626e+00, -1.24527568e-01],
       [-1.07818381e+00,  6.73800101e-01, -2.18503986e+00]])

Dot product

In [172]:
s2= np.arange(12).reshape(3,4)
s3= np.arange(12,24).reshape(4,3)

In [174]:
s2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [176]:
s3

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [178]:
np.dot(s2,s3) #dot product of s2, s3

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

Log and Exponenets

In [181]:
np.exp(s2)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04]])

Round

In [184]:
#Round to the nearest integer
arr= np.array([1.2,2.7,3.5,4.9])
rounded_arr = np.round(arr)
print(rounded_arr)

[1. 3. 4. 5.]


In [188]:
#Round to two decimals
arr= np.array([1.234, 2.567, 3.891])
rounded_arr = np.round(arr, decimals=2)
print( rounded_arr)

[1.23 2.57 3.89]


In [196]:
#randomly
np.round(np.random.random((2,3))*100)

array([[75., 83., 32.],
       [19., 79., 20.]])

Floor

In [199]:
arr = np.array([1.2,2.7,3.5,4.9])
floored_arr = np.floor(arr)
print(floored_arr)

[1. 2. 3. 4.]


In [201]:
np.floor(np.random.random((2,3))*100)

array([[36., 17., 28.],
       [11., 69., 33.]])

Ceil

In [204]:
arr= np.array([1.2,2.7,3.5,4.9])
ceiled_arr= np.ceil(arr)
print(ceiled_arr)

[2. 3. 4. 5.]


In [208]:
np.ceil(np.random.random((2,3))*100)

array([[10., 93.,  8.],
       [94., 58., 23.]])

Indexing

In [289]:
p1= np.arange(10)
p2= np.arange(12).reshape(3,4)
p3= np.arange(8).reshape(2,2,2)

In [213]:
p1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [215]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [217]:
p3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [225]:
p1[0]

0

In [227]:
p1[-1]

9

In [229]:
p2[1,2] # row 1, and 2nd index

6

In [231]:
p2[2,3]

11

In [233]:
p2[1,0]

4

In [235]:
p3[1,0,1] # in 3D, consist of 2 matrix. [1,0,1] here 1 means 2nd matrix, 0 means 1st row and 1 means 2nd number

5

In [237]:
p3[0,1,0] #here 0 means 1st matrix, 1 means 2nd row and 0 means 1st number

2

In [239]:
p3[0,0,0]

0

In [241]:
p3[1,1,0]

6

Slicing

In [249]:
#slicing in 1D
p1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [251]:
p1[2:5] #output number from 2nd index to n-1 index

array([2, 3, 4])

In [253]:
p1[2:5:2] #output number from 2nd index to n-1 index with 2 steps skiping

array([2, 4])

In [255]:
#slicing in 2D
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [257]:
p2[0,:] #total first row

array([0, 1, 2, 3])

In [259]:
p2[:,2]

array([ 2,  6, 10])

In [261]:
p2[1:3]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [263]:
p2[1:3,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [265]:
p2[::2,::3] # first : means all row and :2 means alternate value , : means all column and :3 means jump for two steps

array([[ 0,  3],
       [ 8, 11]])

In [267]:
p2[::2]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

In [271]:
p2[::2, 1::2]

array([[ 1,  3],
       [ 9, 11]])

In [273]:
p2[1,::3]

array([4, 7])

In [275]:
p2[0:2]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [277]:
p2[0:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [279]:
p2[0:2]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [285]:
p2[0:2, 1::2]

array([[1, 3],
       [5, 7]])

In [291]:
#slicing in 3D
p3= np.arange(27).reshape(3,3,3)
p3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [295]:
p3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [297]:
p3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [299]:
p3[0]

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [301]:
p3[0,1,:]

array([3, 4, 5])

In [303]:
p3[1,:,1]

array([10, 13, 16])

In [305]:
p3[2,1:]

array([[21, 22, 23],
       [24, 25, 26]])

In [307]:
p3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [309]:
p3[0::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [311]:
p3[0::2, 0] #for rows

array([[ 0,  1,  2],
       [18, 19, 20]])

In [313]:
p3[0::2, 0 ,::2] #for columns

array([[ 0,  2],
       [18, 20]])

iterating

In [316]:
p1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [318]:
#Looping in 1D array
for i in p1:
    print (i)

0
1
2
3
4
5
6
7
8
9


In [320]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [322]:
#Looping on 2D array
for i in p2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [324]:
p3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [326]:
for i in p3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [328]:
#print all the items in 3D using nditer ---.first convert in to 1D and applying Loop
for i in np.nditer(p3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


Reshaping

In [331]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [333]:
#Transpose
np.transpose(p2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [335]:
#also
p2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [337]:
p3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [339]:
p3.T

array([[[ 0,  9, 18],
        [ 3, 12, 21],
        [ 6, 15, 24]],

       [[ 1, 10, 19],
        [ 4, 13, 22],
        [ 7, 16, 25]],

       [[ 2, 11, 20],
        [ 5, 14, 23],
        [ 8, 17, 26]]])

In [341]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [343]:
#Ravel = converted to 1D
p2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [345]:
p3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

Stacking

In [348]:
#Horizontal Stacking
w1 = np.arange(12).reshape(3,4)
w2 = np.arange(12,24).reshape(3,4)

In [350]:
w1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [352]:
w2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [354]:
np.hstack((w1,w2)) #using hastack for horizontal stacking

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [356]:
#vertical stacking
np.vstack((w1,w2))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

Splitting (opposite of Stacking)

In [360]:
w1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [362]:
#Horizontal splitting
np.hsplit(w1,2) #splitting by 2

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [364]:
np.hsplit(w1,4)

[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

In [366]:
w2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [368]:
#Vertical splitting
np.vsplit(w2,3) #splitting into 3 rows

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]